### PR TITLE
manually add aarch64/ppc64le

### LINKED ISSUE #47: Build with arm64 support
It would be nice to use this with arm64, pip installing it works. I tried adding this to the needs-migration thing, but it doesn't seem like the bot did it's magic.

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

refs:
- fixes #47 (hopefully!)

notes:
- the migration claims there's a circular dependency with `black`... but i don't see aforementioned hue (value?) anywhere in here... here's hoping!

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
Drone looking good for `linux_aarch64`, trying azure for `linux_ppc64le`...

**Comment by bollwyvl** [comment]
Hm, same issue as travis:
```
+ conda install --yes --quiet conda-forge-ci-setup=3 conda-build pip -c conda-forge
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.

ResolvePackageNotFound: 
  - conda==4.8.5

```

**Comment by xhochy** [comment]
Thanks!

**Comment by bollwyvl** [comment]
Hooray ppc working!

**Pull request merged**
